export default {
  GET_COINS: "GET_COINS",
  SET_COINS: "SET_COINS",
  SWAP_COINS: "SWAP_COINS",
  GET_MARKET_INFO: "GET_MARKET_INFO",
  VALIDATE_ADDRESS: "VALIDATE_ADDRESS",
  ADDRESS_ISVALID: "ADDRESS_ISVALID",
  CREATE_TX: "CREATE_TX",
  GET_TX_STATUS: "GET_TX_STATUS",

  LOADING: "LOADING",
  ERROR: "ERROR",
  RESET_ERROR: "RESET_ERROR"
};
